FROM golang:1.19.0-alphine3.15
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 go build -o /bin/app ./tools/turn

FROM alphine
WORKDIR /src

COPY --from=0 /bin/app /bin/app

ENTRYPOINT ["/bin/app"]
